### ISSUE TITLE
你好可以添加一下 ipad 2018 pro 16.3.1 支持吗 a12x

### ISSUE THREAD

**Issue by BuLu0208** [braumye/simplekfd-ipad-ipa#10]
你好可以添加一下 ipad 2018 pro 16.3.1 支持吗 a12x

**Comment by braumye** [comment]
https://github.com/camenling/simplekfd_ipa 试过这个吗？

**Comment by BuLu0208** [comment]
> https://github.com/camenling/simplekfd_ipa试过这个吗？

点击安装就直接闪退   需要进行设置什么吗

**Comment by braumye** [comment]
看看setting是landa还是smith，可以切换试试，如果还是闪退就多试试吧，我也没办法了

**Comment by khoald92vn** [comment]
I still cannot install trollstore on my Ipad 8,1 ios 16.3.1 using URL above and yours. It restarts every i push install trollstore button

**Comment by khoald92vn** [comment]
[``](https://1drv.ms/v/s!AlqNXos5hlrrhL0NazCLnVqbLBaQ6g?e=t2KF7e)

**Comment by braumye** [comment]
[SimpleKFD_braumye_iPad_v108.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13856493/SimpleKFD_braumye_iPad_v108.ipa.zip)

这个版本添加了16.3.1，看看能不能行

**Comment by khoald92vn** [comment]
> [SimpleKFD_braumye_iPad_v108.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13856493/SimpleKFD_braumye_iPad_v108.ipa.zip)
> 
> 这个版本添加了16.3.1，看看能不能行

I tried but still no luck. Sometime ipad is restarted, sometime app is forced close

**Comment by braumye** [comment]
你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

**Comment by khoald92vn** [comment]
> 你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

Thank you. I installed Trollstore success using misaka 8.2.0. Tried 4-5 times to apply kopen

**Comment by braumye** [comment]
> > 你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
> 
> Thank you. I installed Trollstore success using misaka 8.2.0. Tried 4-5 times to apply kopen

Did you switch to smith or are you sticking with landa?

**Comment by khoald92vn** [comment]
> > > 你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
> > 
> > 
> > Thank you. I installed Trollstore success using misaka 8.2.0. Tried 4-5 times to apply kopen
> 
> Did you switch to smith or are you sticking with landa?

I haven't even gone into the settings to adjust it so I think the default is landa

**Comment by braumye** [comment]
> > > > 你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
> > > 
> > > 
> > > Thank you. I installed Trollstore success using misaka 8.2.0. Tried 4-5 times to apply kopen
> > 
> > 
> > Did you switch to smith or are you sticking with landa?
> 
> I haven't even gone into the settings to adjust it so I think the default is landa

thx
