### ISSUE TITLE
你好可以支持 20pro 16.4 8.10芯片 蜂窝版嘛

### ISSUE THREAD

**Issue by Yanson0219** [braumye/simplekfd-ipad-ipa#11]
你好可以支持 20pro 16.4 8.10芯片 蜂窝版嘛
试过很多次misaka 以及pureKFD 都没有成功

**Comment by braumye** [comment]
可以尝试klee大佬封装的SimpleKFD专版，只支持8,10的16.2-16.5
[SimpleKFD_klee_秋名山.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13852071/SimpleKFD_klee_.ipa.zip)

**Comment by Yanson0219** [comment]
牛逼 弄好了
