### ISSUE TITLE
安装成功后在哪里找ts Helper入口？

### ISSUE THREAD

**Issue by tysb7** [braumye/simplekfd-ipad-ipa#12]
安装成功后在哪里找ts Helper入口？

**Comment by braumye** [comment]
打开你的Tips，如果Tips闪退就强制重启后再打开Tips，如果Tips可以正常打开但是没有变成TsHelper，则重新安装Tips然后再次Install，全程需要全局科学上网，确保iPad可以访问GitHub

**Comment by tysb7** [comment]
感谢，`iPad 8st` `16.6.1` 成功了！
