### ISSUE TITLE
iPad 14.3有希望吗？

### ISSUE THREAD

**Issue by narrative-lion** [braumye/simplekfd-ipad-ipa#13]

**Comment by braumye** [comment]
M2设备因为无法提取偏移值所以无法支持，抱歉☹️

**Comment by braumye** [comment]
如果你的系统在16.5.1及以下，可以尝试PureKFD

**Comment by braumye** [comment]
可以试试这个 https://github.com/braumye/PureKFD/releases/tag/v1.0.0
