### ISSUE TITLE
老哥老哥，iPad pro M1芯片的点install trollstore那个按钮就闪退了

### ISSUE THREAD

**Issue by wc90** [braumye/simplekfd-ipad-ipa#14]
老哥，iPad pro13,8(A2378)，M1芯片的，可以安装软件，顺利打开了，但是点左上角菜单最后一项install trollstore那个按钮就闪退了，请问我应该咋整才能安装trollstore？

**Comment by braumye** [comment]
系统多少？闪退只能多试试了

**Comment by wc90** [comment]
系统忘了说了，16.6

**Comment by wc90** [comment]
好的，我再试试，崩溃的一周😭

**Comment by stobhk** [comment]
是不是大存储，1T以上的 ？ 1T以上的运存是16G  1T以下的是8G 。 

如果是你是1T及以上版本的，你试试下载几个大型游戏，同时开几个 ，过2分钟后， 然后再试 ， 之前我有TG朋友是这个大运存的成功了。

**Comment by stobhk** [comment]
反正M1 16.6.1 大运存版本的ipadpro  挺难安装的

**Comment by wc90** [comment]
好的好的，我是256的…我多试试，多谢老哥了

**Comment by wc90** [comment]
> 系统多少？闪退只能多试试了感谢老哥，新版安装成功了

**Comment by braumye** [comment]
恭喜

**Comment by stobhk** [comment]
> > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了

看到你能成功，而我的 M1  2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。 
我的是ipadpro(型号ipad13,7)   M1  2T存储(16G运存) 插卡版 ， 系统16.6.1  .

**Comment by stobhk** [comment]
> > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了
看到你能成功，恭喜啦！ 

我的 M1 2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。
我的是ipadpro(型号ipad13,7) M1 2T存储(16G运存) 插卡版 ， 系统16.6.1 .

**Comment by braumye** [comment]
> > > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了
> > > 看到你能成功，恭喜啦！
> 
> 我的 M1 2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。 我的是ipadpro(型号ipad13,7) M1 2T存储(16G运存) 插卡版 ， 系统16.6.1 .

使用过最新的purekfd吗？purekfd的成功率也还可以的

**Comment by stobhk** [comment]
> > > > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了
> 
> > > > 看到你能成功，恭喜啦！
> 
> > 
> 
> > 我的 M1 2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。 我的是ipadpro(型号ipad13,7) M1 2T存储(16G运存) 插卡版 ， 系统16.6.1 .
> 
> 
> 
> 使用过最新的purekfd吗？purekfd的成功率也还可以的

一直用的是能下载到的purekfd最新版， 前面100次左右都是在purekfd安装助手时直接闪退。 
后来有兄弟跟我说，M1的1T和2T版本是大内存，安装巨魔助手前  最好开几个大型游戏。
现在每次重启后 如果提示没变化，重装提示后 都会开几个游戏， 然后再开梯子安装助手， 
虽然现在每次都会 弹出安装成功的框，但强制重启后 提示一直没变化。  所以…如果有可能，还请拜托看看大内存的版本啊，感谢感谢啊！

**Comment by braumye** [comment]
> > > > > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了
> > 
> > 
> > > > > 看到你能成功，恭喜啦！
> > 
> > 
> > > 
> > 
> > 
> > > 我的 M1 2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。 我的是ipadpro(型号ipad13,7) M1 2T存储(16G运存) 插卡版 ， 系统16.6.1 .
> > 
> > 
> > 使用过最新的purekfd吗？purekfd的成功率也还可以的
> 
> 一直用的是能下载到的purekfd最新版， 前面100次左右都是在purekfd安装助手时直接闪退。 后来有兄弟跟我说，M1的1T和2T版本是大内存，安装巨魔助手前 最好开几个大型游戏。 现在每次重启后 如果提示没变化，重装提示后 都会开几个游戏， 然后再开梯子安装助手， 虽然现在每次都会 弹出安装成功的框，但强制重启后 提示一直没变化。 所以…如果有可能，还请拜托看看大内存的版本啊，感谢感谢啊！

所以你也是全都是installed但是没有替换？可以试试这一版本，大力出奇迹，一次install执行10次替换 https://github.com/braumye/PureKFD/releases/tag/v1.0.1

**Comment by stobhk** [comment]
> > > > > > 系统多少？闪退只能多试试了感谢老哥，新版安装成功了
> > > 
> > > 
> > > > > > 看到你能成功，恭喜啦！
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 我的 M1 2T大存储 已经搞了有200来遍了 ，没成功 。人已经傻了 。 我的是ipadpro(型号ipad13,7) M1 2T存储(16G运存) 插卡版 ， 系统16.6.1 .
> > > 
> > > 
> > > 使用过最新的purekfd吗？purekfd的成功率也还可以的
> > 
> > 
> > 一直用的是能下载到的purekfd最新版， 前面100次左右都是在purekfd安装助手时直接闪退。 后来有兄弟跟我说，M1的1T和2T版本是大内存，安装巨魔助手前 最好开几个大型游戏。 现在每次重启后 如果提示没变化，重装提示后 都会开几个游戏， 然后再开梯子安装助手， 虽然现在每次都会 弹出安装成功的框，但强制重启后 提示一直没变化。 所以…如果有可能，还请拜托看看大内存的版本啊，感谢感谢啊！
> 
> 所以你也是全都是installed但是没有替换？可以试试这一版本，大力出奇迹，一次install执行10次替换 https://github.com/braumye/PureKFD/releases/tag/v1.0.1

大哥大哥，果真大力出了奇迹 ，安装了4次 （算起来连续安装了40次），提示应用直接闪退了    强制重启 出现了，感谢大佬！大佬威武啊！
