### ISSUE TITLE
ipad7.3

### ISSUE THREAD

**Issue by 39c5bb999** [braumye/simplekfd-ipad-ipa#15]
可以添加一下iPad7.3的16.6吗

**Comment by braumye** [comment]
iPad7因为无法提取偏移值而无法支持，抱歉

**Comment by braumye** [comment]
你好，想问一下你这设备是可以直接越狱吗？有尝试直接安装TrollHelper来安装TrollStore吗？

**Comment by 39c5bb999** [comment]
> 你好，想问一下你这设备是可以直接越狱吗？有尝试直接安装TrollHelper来安装TrollStore吗？

你好，我有看到网上关于越狱安装TrollStore的方法，但是因为我的电脑是amd，没法使用那个方法

**Comment by 39c5bb999** [comment]
请问是支持了吗 我刚刚去尝试了下 没有成功

**Comment by braumye** [comment]
没有支持，因为无法提取iPad7,x的offset。

安装官方说法，只能考虑通过越狱来安装TrollStore，抱歉。

**Comment by braumye** [comment]
请尝试misaka8.2.0，说不定可以使用
