### ISSUE TITLE
Please add support for iPad Pro 11inch A12Z (iPad 8,9) on 16.4

### ISSUE THREAD

**Issue by Galafador** [braumye/simplekfd-ipad-ipa#16]
here's the ipsw link if you need it. Thank you in advance~!
https://updates.cdn-apple.com/2023WinterSeed/fullrestores/032-66024/FDDEEDA0-47C6-44A4-872C-5B2BA23F9EE2/iPad_Pro_A12X_A12Z_16.4_20E246_Restore.ipsw

**Comment by braumye** [comment]
[SimpleKFD_braumye_iPad_8_9_16_4.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13853838/SimpleKFD_braumye_iPad_8_9_16_4.ipa.zip)

Could you help me test it out? If it crashes, please try a few more times. Thanks a lot!

**Comment by Galafador** [comment]
crashed once, and then worked the second time. thank you so much! 

![IMG_5232](https://github.com/braumye/simplekfd-ipad-ipa/assets/106337017/e85a0c25-68cd-47e0-ba7e-075710560633)

**Comment by braumye** [comment]
Thanks for helping with the testing. I'll add the changes and release a new version.
