### ISSUE TITLE
Ipadpro 2020 16.6.1 success 

### ISSUE THREAD

**Issue by vestw** [braumye/simplekfd-ipad-ipa#17]
特来感谢，试过很多软件，你的成功了。
一开始出现instanted tshelper激动坏了。结果提示这一步卡住了。直接点，重启点，删掉在下点，都不行。从下午点到现在，终于成功了…

Special thanks, after trying a lot of software, you succeeded.
At the beginning, the tshelper burned out,but still the tips didnt change 
. Click it directly, click Restart, or delete it then reinstall but it doesn't work.
 From pm to now, it has been successful...

**Comment by braumye** [comment]
恭喜上车
