### ISSUE TITLE
Please add support for iPad Pro 11inch A12Z (iPad 8,9) on 16.3.1

### ISSUE THREAD

**Issue by kenlwb01818** [braumye/simplekfd-ipad-ipa#18]
Thanks！

**Comment by braumye** [comment]
Could you help me test it out? If it crashes, please try a few more times. Thanks a lot! 

[SimpleKFD_braumye_iPad_8_x_16_3_1.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13854685/SimpleKFD_braumye_iPad_8_x_16_3_1.ipa.zip)

**Comment by kenlwb01818** [comment]
> 你能帮我测试一下吗？如果崩溃了，请多尝试几次。多谢！
> 
> [SimpleKFD_braumye_iPad_8_x_16_3_1.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13854685/SimpleKFD_braumye_iPad_8_x_16_3_1.ipa.zip)

Hi, I tried twenty times and it either restarted or crashed.

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

Please try using [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0). This version includes a dynamic offset finding tool, which in theory, should support all iOS 16+ devices.
