### ISSUE TITLE
iPad Air 3, 11,3 16.6.1 一直闪退 能不能麻烦加下支持 球球了

### ISSUE THREAD

**Issue by dxyyyy** [braumye/simplekfd-ipad-ipa#2]

**Comment by braumye** [comment]
如果闪退就没办法了，闪退说明偏移值不对，我这边无能为力，很抱歉

**Comment by x-dr** [comment]
![be6aa927453a8c87fca3c968c79a0089](https://github.com/braumye/simplekfd-ipad-ipa/assets/79109673/632f0e63-e5d5-445d-8190-60f2740c7197)
  
闪退重启就多试几次  可以的
