### ISSUE TITLE
Please support iPad8,9 A12Z 16.2

### ISSUE THREAD

**Issue by Litjxnu** [braumye/simplekfd-ipad-ipa#24]

**Comment by braumye** [comment]
[SimpleKFD_braumye_iPad_v108.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13856493/SimpleKFD_braumye_iPad_v108.ipa.zip)

This version adds support for 16.2, 16.3.1, and 16.4. Could you help me test it out? If it crashes, please try a few more times. Thanks a lot!

**Comment by Litjxnu** [comment]
I tried for 40 minutes and don't remember how many times. When using landa, it will crash most of the time and restart occasionally. When it crashes, it will get stuck if you use smith. If you use smith, it will definitely restart.

**Comment by braumye** [comment]
请尝试使用purekfd4.6版本，选择smith，3072+172或者3072+256，除此之外暂时无法提供其他帮助，非常抱歉

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

Please try using [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0). This version includes a dynamic offset finding tool, which in theory, should support all iOS 16+ devices.
