### ISSUE TITLE
Hello, iPad pro 2018 (16.5.1) did not have a single successful example🥹🥹🥹🥹🥹🥹

### ISSUE THREAD

**Issue by vgg102** [braumye/simplekfd-ipad-ipa#25]

**Comment by vgg102** [comment]
iPad pro 2018 No, please make one. Thank you very much!

**Comment by braumye** [comment]
What's your iPad model? Like iPad8,9. Have you tried the latest version of PureKFD?

**Comment by vgg102** [comment]
> 您的 iPad 型号是什么？像iPad8、9。您尝试过最新版本的 PureKFD 吗？



> 您的 iPad 型号是什么？像 iPad8、9。您尝试使用最新版本的 PureKFD 吗？

Thank you for your reply. Mine is iPad 8.1 (16.5.1).

**Comment by vgg102** [comment]
> 您的 iPad 型号是什么？像iPad8、9。您尝试过最新版本的 PureKFD 吗？

Tried all the versions

**Comment by braumye** [comment]
我这边单独验证过iPad8,1 16.5.1，确实行不通，目前暂时没有其他办法，很抱歉

**Comment by vgg102** [comment]
> 我单独验证过iPad8,1 16.5.1，确实行不通，目前暂时没有其他办法，很遗憾
Thank you very much！I will continue to wait
