### ISSUE TITLE
能添加一下 iPad8,9 A12Z 16.3 支持吗？

### ISSUE THREAD

**Issue by Lhw-Arthas** [braumye/simplekfd-ipad-ipa#26]

**Comment by misaka-fans** [comment]
iPad8,9（a12z） 16.3.1同求，失败，紫屏重启或者闪退

**Comment by braumye** [comment]
16.5以下还需要调整

**Comment by braumye** [comment]
16.3请尝试使用purekfd4.6版本，选择smith，3072+172或者3072+256，除此之外暂时无法提供其他帮助，非常抱歉

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

Please try using [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0). This version includes a dynamic offset finding tool, which in theory, should support all iOS 16+ devices.
