### ISSUE TITLE
iPad8,3 A12X iOS16.6 not working

### ISSUE THREAD

**Issue by KernelFox0** [braumye/simplekfd-ipad-ipa#27]
Either crashes or panics

**Comment by braumye** [comment]
https://github.com/braumye/PureKFD/releases/tag/v1.0.1 

I think you can try it.

**Comment by KernelFox0** [comment]
Sadly it did the same. I heard that iPads, especially A12X/A12Z are really problematic and will need more work. Thanks for your help anyways.

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

Please try using [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0). This version includes a dynamic offset finding tool, which in theory, should support all iOS 16+ devices.

**Comment by KernelFox0** [comment]
It worked
