### ISSUE TITLE
Unsupported device iPad14,5-A - iOS 16.5.1

### ISSUE THREAD

**Issue by Dragoy** [braumye/simplekfd-ipad-ipa#28]
Unsupported device iPad14,5-A - iOS 16.5.1:

![image](https://github.com/braumye/simplekfd-ipad-ipa/assets/4968313/e380ff4b-949a-432c-88e2-489402b31c2f)

**Comment by braumye** [comment]
https://github.com/PureKFD/PureKFD/releases/tag/5.0

**Comment by Dragoy** [comment]
> https://github.com/PureKFD/PureKFD/releases/tag/5.0

It doesn't work for me, it says that the application was replaced, but after restarting the device, the Tips application remains the same.

**Comment by braumye** [comment]
https://github.com/braumye/PureKFD/releases/tag/v1.0.1

You can try it.

**Comment by Dragoy** [comment]
> https://github.com/braumye/PureKFD/releases/tag/v1.0.1
> 
> You can try it.
Thanks, I managed to do this on version 1.0.0. It was all the fault of the stage manager mode turned on.When I turned it off, after rebooting everything opened as expected. I think iPad users need to be warned about this somewhere.

**Comment by braumye** [comment]
congrats!
