### ISSUE TITLE
你好可以添加一下 ipad 2018 pro 16.3 / iPad8,3 * iOS16.3 (20D47) 支持吗 a12x

### ISSUE THREAD

**Issue by yipengni** [braumye/simplekfd-ipad-ipa#29]
尝试了最新misaka \simplekfd\purekfd 目前都还未成功

**Comment by braumye** [comment]
16.3请尝试使用purekfd4.6版本

**Comment by yipengni** [comment]
感谢braumye快速的回复！   我尝试了purekfd4.6，您说的“选择smith，3072+172或者3072+256”是下图三个红色圈中的选项么？
![爱思投屏_20240109114805](https://github.com/braumye/simplekfd-ipad-ipa/assets/152131845/693e958b-b727-414b-8ff6-d518fd6527ef)

**Comment by braumye** [comment]
是的，如果崩溃请尝试多次

**Comment by yipengni** [comment]
多谢回复！但还是无法成功
尝试了多次purekfd4.6 选择smith，3072+192或者3072+256 。都是点击 install trollstrore Helper(KFD) 之后立即黑屏重启

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

**Comment by jarryson** [comment]
> 请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

点击了一会就重启。。。之前是闪退或者重启

**Comment by braumye** [comment]
> > 请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
> 
> 点击了一会就重启。。。之前是闪退或者重启

请多尝试，因为kfd不稳定
