### ISSUE TITLE
Please support iPad14,3 ios16.6(20G75)

### ISSUE THREAD

**Issue by SundayCoding** [braumye/simplekfd-ipad-ipa#3]
Please support iPad14,3 ios16.6(20G75)

**Comment by braumye** [comment]
Sorry I can't support the m2 device.

**Comment by braumye** [comment]
[purekfd_braumye_m2_16_x.ipa.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13855738/purekfd_braumye_m2_16_x.ipa.zip)

Could you help me test it out? If it crashes, please try a few more times. Thanks a lot!

**Comment by BlackVegetable19** [comment]
TS helper installer worked on first try, but it took 3 tries for the Tips app to change. I have TS installed now. Thank you so much!!

![IMG_0010](https://github.com/braumye/simplekfd-ipad-ipa/assets/40974595/6ad7d9ae-d309-4b66-a5da-a25cbc55b9a3)

**Comment by SundayCoding** [comment]
> Could you help me test it out? If it crashes, please try a few more times. Thanks a lot!

successful thanks
