### ISSUE TITLE
ipad 8,3 16.6.1 Flashbacks no matter what version

### ISSUE THREAD

**Issue by cxxxx9527** [braumye/simplekfd-ipad-ipa#31]
iPad8,3 IOS16.6.1 A12X （20G81） Any version of the installation crashes

**Comment by braumye** [comment]
You have a couple of options: 

- Keep retrying until you decide to give up, or 

- Try PureKFD v5. You can find it here: https://github.com/PureKFD/PureKFD/releases/tag/5.0.

**Comment by cxxxx9527** [comment]
还有机会直接添加 iPad8,3 IOS16.6.1 A12X （20G81）偏移量吗

**Comment by braumye** [comment]
已经添加过了，所以如果闪退，只能多试试

**Comment by braumye** [comment]
PureKFD的成功率也不错，你可以试试

**Comment by cxxxx9527** [comment]
如果都成功不了的话 是不是只能放弃

**Comment by braumye** [comment]
我翻了dc记录，找到一个之前8,3 16.6.1成功的ipa，你可以试试 https://discord.com/channels/1156843198799421490/1171106974776172595/1192753762561949746

**Comment by cxxxx9527** [comment]
提示我没有权限访问频道  cxxxx9527  这是我的用户名 期待能进入频道拿到IPA

**Comment by braumye** [comment]
我手机把ipa保存下来了，issue没办法上传ipa，搞了个release上传了ipa，你可以试试 https://github.com/braumye/simplekfd-ipad-ipa/releases/tag/v0.0.1

**Comment by cxxxx9527** [comment]
我想说这IPA真的太棒了 解决了我的问题 我觉得您应该发布一个专版 我利用SImpleKFD成功安装

**Comment by braumye** [comment]
恭喜
