### ISSUE TITLE
可以添加对iPad7.4的支持吗？

### ISSUE THREAD

**Issue by panchengda1984** [braumye/simplekfd-ipad-ipa#32]
可以添加对iPad7.4的支持吗？

**Comment by braumye** [comment]
很抱歉，由于无法提取iPad7,x的offset，所以无法支持。

针对iPad7,x机型，请使用越狱来安装TrollStore。

**Comment by braumye** [comment]
如果你的系统是iOS16.x，请尝试misaka8.2.0
