### ISSUE TITLE
你好可以添加一下  ipadpro  2021 M1 16.2  的支持吗 我用了purekfd

### ISSUE THREAD

**Issue by BuLu0208** [braumye/simplekfd-ipad-ipa#33]

**Comment by BuLu0208** [comment]
你好可以添加一下 ipadpro 2021 M1 16.2 的支持吗 我用了purekfd还是不行

**Comment by braumye** [comment]
请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
