### ISSUE TITLE
老哥，iPad8,7 iOS16.6 是不是不支持

### ISSUE THREAD

**Issue by cimisi** [braumye/simplekfd-ipad-ipa#34]
一直闪退或者重启。。。

**Comment by braumye** [comment]
已经添加过iPad8,7的偏移，可以多试试。

建议也尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

**Comment by cimisi** [comment]
> 已经添加过iPad8,7的偏移，可以多试试。
> 
> 建议也尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。

还是一直重启。。。是有可能会成功是吗？
MIsaka 8.2.0 在我的设备上也是会重启，不知道出现了什么问题

**Comment by braumye** [comment]
重启是正常的，因为kfd不稳定，有可能成功，建议一直尝试
