### ISSUE TITLE
Could you please support ipad pro 2020 A12Z 16.3.1?

### ISSUE THREAD

**Issue by phamthai1912** [braumye/simplekfd-ipad-ipa#4]
Could you please support ipad pro 2020 A12Z 16.3.1? It's showing a popup your device is unsupported

**Comment by braumye** [comment]
Sorry about that, but since your system is below version 16.5, I would need to modify the offsets individually, and I'm unable to do that. You might want to try using Misaka instead.

**Comment by phamthai1912** [comment]
Hi bro,

I tried Misaka 8.1.1 (latest version) but no lucks. Hope you can fix this when you have free time. Thanks bro in advance.
Btw, I can help to do testing if you need my support :)

**Comment by phamthai1912** [comment]
Hi bro, below is offset of ipad pro 2020 a12z 16.3.1. I tested and installed trollstore successfully on my device. You can use it to add your build.

// ipad a12z 16.3.1
    {
        .kern_version = "Darwin Kernel Version 22.3.0: Wed Jan  4 21:24:51 PST 2023; root:xnu-8792.82.2~1/RELEASE_ARM64_T8020",
        .build_version = "20D67",
        .device_id = "iPad8,10",
        .fileglob__fg_ops = 0x28,
        .fileglob__fg_data = 0x40 - 8,
        .fileops__fo_kqfilter = 0x30,
        // .fileproc__fp_iocount = 0x0000,
        // .fileproc__fp_vflags = 0x0004,
        // .fileproc__fp_flags = 0x0008,
        // .fileproc__fp_guard_attrs = 0x000a,
        // .fileproc__fp_glob = 0x0010,
        // .fileproc__fp_guard = 0x0018,
        // .fileproc__object_size = 0x0020,
        .fileproc_guard__fpg_guard = 0x8,
        .kqworkloop__kqwl_state = 0x10,
        .kqworkloop__kqwl_p = 0x18,
        .kqworkloop__kqwl_owner = 0xd0,
        .kqworkloop__kqwl_dynamicid = 0xd0 + 0x18,
        .kqworkloop__object_size = 0x108,
        .pmap__tte = 0x0,
        .pmap__ttep = 0x8,
        .proc__p_list__le_next = 0x0,
        .proc__p_list__le_prev = 0x8,
        .proc__p_pid = 0x60,
        .proc__p_fd__fd_ofiles = 0xf8,
        .proc__object_size = 0x538,
        .pseminfo__psem_usecount = 0x04,
        .pseminfo__psem_uid = 0x0c,
        .pseminfo__psem_gid = 0x10,
        .pseminfo__psem_name = 0x14,
        .pseminfo__psem_semobject = 0x38,
        // .psemnode__pinfo = 0x0000,
        // .psemnode__padding = 0x0008,
        // .psemnode__object_size = 0x0010,
        .semaphore__owner = 0x28,
        .specinfo__si_rdev = 0x18,
        .task__map = 0x28,
        // .task__threads__next = 0x80 - 0x28, ?????
        .task__threads__next = 0x368 - 0x18,
        .task__threads__prev = 0x80 - 0x28 + 8,
        .task__itk_space = 0x300,
        .task__object_size = 0x628,
        // .thread__task_threads__next = 0x368 - 0x18, ?????
        .thread__task_threads__next = 0x80 - 0x28,
        .thread__task_threads__prev = 0x368 - 0x18 + 8,
        .thread__map = 0x368,
        .thread__thread_id = 0x400,
        .thread__object_size = 0x4a8,
        .uthread__object_size = 0xfffffffffffffb58,
        .vm_map_entry__links__prev = 0x00,
        .vm_map_entry__links__next = 0x08,
        .vm_map_entry__links__start = 0x10,
        .vm_map_entry__links__end = 0x18,
        .vm_map_entry__store__entry__rbe_left = 0x20,
        .vm_map_entry__store__entry__rbe_right = 0x28,
        .vm_map_entry__store__entry__rbe_parent = 0x30,
        .vnode__v_un__vu_specinfo = 0x78,
        ._vm_map__hdr__links__prev = 0x00 + 0x10,
        ._vm_map__hdr__links__next = 0x08 + 0x10,
        ._vm_map__hdr__links__start = 0x10 + 0x10,
        ._vm_map__hdr__links__end = 0x18 + 0x10,
        ._vm_map__hdr__nentries = 0x30,
        ._vm_map__hdr__rb_head_store__rbh_root = 0x38,
        ._vm_map__pmap = 0x40,
        ._vm_map__hint = 0x90 + 0x08,
        ._vm_map__hole_hint = 0x90 + 0x10,
        ._vm_map__holes_list = 0x90 + 0x18,
        ._vm_map__object_size = 0x0,
        .kernelcache__kernel_base = 0xfffffff007004000,
        .kernelcache__cdevsw = 0xfffffff00a325178,
        .kernelcache__gPhysBase = 0xfffffff007867d48,
        .kernelcache__gPhysSize = 0xfffffff007867d48 + 8,
        .kernelcache__gVirtBase = 0xfffffff007865f28,
        .kernelcache__perfmon_devices = 0xfffffff00a360380,
        .kernelcache__perfmon_dev_open = 0xfffffff007ee3398,
        .kernelcache__ptov_table = 0xfffffff00781b288,
        .kernelcache__vm_first_phys_ppnum = 0xfffffff00a35f800,
        .kernelcache__vm_pages = 0xfffffff0078180c0,
        .kernelcache__vm_page_array_beginning_addr = 0xfffffff00781a248,
        .kernelcache__vm_page_array_ending_addr = 0xfffffff00a35f7f8,
        .kernelcache__vn_kqfilter = 0xfffffff007f35a20,
    },

**Comment by braumye** [comment]
Thanks. [v1.0.6](https://github.com/braumye/simplekfd-ipad-ipa/releases/tag/v1.0.6) has been released.

**Comment by braumye** [comment]
> Hi @braumye , below is offset of ipad pro 2020 a12z 16.3.1. I tested and installed trollstore successfully on my device. You can use it to add your build.
> 
> // ipad a12z 16.3.1 { .kern_version = "Darwin Kernel Version 22.3.0: Wed Jan 4 21:24:51 PST 2023; root:xnu-8792.82.2~1/RELEASE_ARM64_T8020", .build_version = "20D67", .device_id = "iPad8,10", .fileglob__fg_ops = 0x28, .fileglob__fg_data = 0x40 - 8, .fileops__fo_kqfilter = 0x30, // .fileproc__fp_iocount = 0x0000, // .fileproc__fp_vflags = 0x0004, // .fileproc__fp_flags = 0x0008, // .fileproc__fp_guard_attrs = 0x000a, // .fileproc__fp_glob = 0x0010, // .fileproc__fp_guard = 0x0018, // .fileproc__object_size = 0x0020, .fileproc_guard__fpg_guard = 0x8, .kqworkloop__kqwl_state = 0x10, .kqworkloop__kqwl_p = 0x18, .kqworkloop__kqwl_owner = 0xd0, .kqworkloop__kqwl_dynamicid = 0xd0 + 0x18, .kqworkloop__object_size = 0x108, .pmap__tte = 0x0, .pmap__ttep = 0x8, .proc__p_list__le_next = 0x0, .proc__p_list__le_prev = 0x8, .proc__p_pid = 0x60, .proc__p_fd__fd_ofiles = 0xf8, .proc__object_size = 0x538, .pseminfo__psem_usecount = 0x04, .pseminfo__psem_uid = 0x0c, .pseminfo__psem_gid = 0x10, .pseminfo__psem_name = 0x14, .pseminfo__psem_semobject = 0x38, // .psemnode__pinfo = 0x0000, // .psemnode__padding = 0x0008, // .psemnode__object_size = 0x0010, .semaphore__owner = 0x28, .specinfo__si_rdev = 0x18, .task__map = 0x28, // .task__threads__next = 0x80 - 0x28, ????? .task__threads__next = 0x368 - 0x18, .task__threads__prev = 0x80 - 0x28 + 8, .task__itk_space = 0x300, .task__object_size = 0x628, // .thread__task_threads__next = 0x368 - 0x18, ????? .thread__task_threads__next = 0x80 - 0x28, .thread__task_threads__prev = 0x368 - 0x18 + 8, .thread__map = 0x368, .thread__thread_id = 0x400, .thread__object_size = 0x4a8, .uthread__object_size = 0xfffffffffffffb58, .vm_map_entry__links__prev = 0x00, .vm_map_entry__links__next = 0x08, .vm_map_entry__links__start = 0x10, .vm_map_entry__links__end = 0x18, .vm_map_entry__store__entry__rbe_left = 0x20, .vm_map_entry__store__entry__rbe_right = 0x28, .vm_map_entry__store__entry__rbe_parent = 0x30, .vnode__v_un__vu_specinfo = 0x78, ._vm_map__hdr__links__prev = 0x00 + 0x10, ._vm_map__hdr__links__next = 0x08 + 0x10, ._vm_map__hdr__links__start = 0x10 + 0x10, ._vm_map__hdr__links__end = 0x18 + 0x10, ._vm_map__hdr__nentries = 0x30, ._vm_map__hdr__rb_head_store__rbh_root = 0x38, ._vm_map__pmap = 0x40, ._vm_map__hint = 0x90 + 0x08, ._vm_map__hole_hint = 0x90 + 0x10, ._vm_map__holes_list = 0x90 + 0x18, ._vm_map__object_size = 0x0, .kernelcache__kernel_base = 0xfffffff007004000, .kernelcache__cdevsw = 0xfffffff00a325178, .kernelcache__gPhysBase = 0xfffffff007867d48, .kernelcache__gPhysSize = 0xfffffff007867d48 + 8, .kernelcache__gVirtBase = 0xfffffff007865f28, .kernelcache__perfmon_devices = 0xfffffff00a360380, .kernelcache__perfmon_dev_open = 0xfffffff007ee3398, .kernelcache__ptov_table = 0xfffffff00781b288, .kernelcache__vm_first_phys_ppnum = 0xfffffff00a35f800, .kernelcache__vm_pages = 0xfffffff0078180c0, .kernelcache__vm_page_array_beginning_addr = 0xfffffff00781a248, .kernelcache__vm_page_array_ending_addr = 0xfffffff00a35f7f8, .kernelcache__vn_kqfilter = 0xfffffff007f35a20, },



._vm_map__hdr__links__prev = 0x00 + 0x10,
._vm_map__hdr__links__next = 0x08 + 0x10,
._vm_map__hdr__links__start = 0x10 + 0x10,
._vm_map__hdr__links__end = 0x18 + 0x10,

.task__threads__next and 
.thread__task_threads__next

only change 6 value?

**Comment by phamthai1912** [comment]
I am not sure. I  got it from offset finder tool. 
![AD3CE7B9-D7A7-4560-9F66-C4DB3BE9B929](https://github.com/braumye/simplekfd-ipad-ipa/assets/16661767/743915dc-984b-495c-8044-d3232988023f)
![3FB34E87-D0CC-490F-89B3-5AF40F771D30](https://github.com/braumye/simplekfd-ipad-ipa/assets/16661767/2465a860-ae32-479c-aac4-afc30a963ad8)
