### ISSUE TITLE
iPad Pro 2018 A12X 16.6是不支持吗？

### ISSUE THREAD

**Issue by tofu2333** [braumye/simplekfd-ipad-ipa#5]
我用了simplekfd-ipad-ipa一直闪退或者重启。好像还没见过a12x成功安装的。

**Comment by braumye** [comment]
确实很多时候是闪退或者重启，但是有人成功的，只能多试试了

**Comment by braumye** [comment]
你好！如果还未成功，请尝试使用 [misaka 8.2.0](https://github.com/straight-tamago/misaka/releases/tag/8.2.0)，该版本添加了偏移动态查找工具，理论上支持所有iOS16+设备。
