### ISSUE TITLE
iPad7 11 16.3可以支持一下吗？

### ISSUE THREAD

**Issue by daxia25881** [braumye/simplekfd-ipad-ipa#6]
iPad7 11 16.3可以支持一下吗？

**Comment by braumye** [comment]
iPad7,11 目前无法提取偏移值，所以也没办法支持，抱歉

**Comment by braumye** [comment]
你好！想问一下你这设备可以直接越狱吗？有尝试过先安装TrollHelper，再通过TrollHelper来安装TrollStore吗？
