### ISSUE TITLE
Add support for iPad Pro 11 (A12X) on 15.7.2 (KFD)

### ISSUE THREAD

**Issue by giovannidirenzo** [braumye/simplekfd-ipad-ipa#7]
i can contribute with the kernelcache file

**Comment by braumye** [comment]
I think we can give it a shot. please paste your kernelcache here.

**Comment by giovannidirenzo** [comment]
[kernel.raw.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13850157/kernel.raw.zip)

this is the kernelcache extracted with img4tool

**Comment by braumye** [comment]
> [kernel.raw.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13850157/kernel.raw.zip)
> 
> this is the kernelcache extracted with img4tool

can you give me the build id (like 20F75) and your Identifier (like iPad8,1)?

**Comment by giovannidirenzo** [comment]
yes, the identifier is iPad8,1 and the build number is 19H218

**Comment by giovannidirenzo** [comment]
if you need this is the unextracted kernelcache 
[kernelcache.release.ipad8.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13850376/kernelcache.release.ipad8.zip)
[kernelcache.release.ipad8b.zip](https://github.com/braumye/simplekfd-ipad-ipa/files/13850377/kernelcache.release.ipad8b.zip)

**Comment by braumye** [comment]
```
offsetexporter: liboffsetfinder64 version: 0.150-1a633df5dd41a9432bd8c684ae5d9b46595bcf22-RELEASE
Init KPF('kernel_15_7_2.raw')
[WARNING] We encountered __TEXT_EXEC section, marking normal __TEXT section as non-executable!
Detected non-slid kernel.
Inited machopatchfinder64 150 1a633df5dd41a9432bd8c684ae5d9b46595bcf22
Kernel version: 8020.241.14~1
Detected iOS 15 kernel
[Error] liboffsetfinder64: failed with exception:
[exception]:
what=not implemented by provider
code=9109519
line=139
file=patchfinder.cpp
commit count=150
commit sha  =1a633df5dd41a9432bd8c684ae5d9b46595bcf22
```

It looks like offsets cannot be extracted. Can you use [c22dev/OffsetFinder](https://github.com/c22dev/OffsetFinder) to generate the offset?

**Comment by giovannidirenzo** [comment]
Yes I know, because the script from offsetfinder uses libpatchfinder/offsetexporter with the example file template_dynamic_info.h that is designed for iOS 16, so offsetfinder can't work without editing, I'm trying with Ghidra but I'm not an expert and so I'm kinda stuck, maybe someone knows how to use libpatchfinder? Or some alternative methods maybe

**Comment by braumye** [comment]
> Yes I know, because the script from offsetfinder uses libpatchfinder/offsetexporter with the example file template_dynamic_info.h that is designed for iOS 16, so offsetfinder can't work without editing, I'm trying with Ghidra but I'm not an expert and so I'm kinda stuck, maybe someone knows how to use libpatchfinder? Or some alternative methods maybe

I'm sorry, I'm not familiar with this, so I'm unable to offer help on it.
